name: Generate Snake Animation

on:
  push:
    branches:
      - main  # Substitua 'main' pela sua branch principal, se for diferente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ajuste a versão do Python conforme necessário

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy  # Exemplo de dependência necessária para o script

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: 'Cristina-Silva15'  # Seu nome de usuário GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake Animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Cristina-Silva15"
          git config --global user.email "165852715+Cristina-Silva15@users.noreply.github.com" 
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
