name: Generate Snake Animation

on:
  push:
    branches:
      - main  # ou master, dependendo do nome da sua branch principal
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: List files before generation
        run: ls -la dist/

      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: List files after generation
        run: ls -la dist/

      - name: Verify SVG file creation
        run: |
          if [ ! -f dist/github-contribution-grid-snake.svg ]; then
            echo "SVG file not found!"
            exit 1
          else
            echo "SVG file found and ready for commit."
          fi

      - name: Commit and Push Snake Animation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
        # Verifique se o token tem permissões adequadas
        # e se o repositório e diretórios são acessíveis
